# SPDX-FileCopyrightText: 2025 Jack Henry
#
# SPDX-License-Identifier: Apache-2.0

nodeLinker: node-modules
enableScripts: true

npmScopes:
  jack-henry:
    npmRegistryServer: "https://registry.npmjs.org"
