// SPDX-FileCopyrightText: 2025 Jack Henry
//
// SPDX-License-Identifier: Apache-2.0

export const SSO_LINK_TYPES = {
  ACCOUNT_OPENING: 'AccountOpening',
  BILL_PAY: 'BillPay',
  BROKERAGE_TOOLS: 'BrokerageTools',
  BROKERAGE_TOOLS_2: 'BrokerageTools2',
  BUDGET_TOOLS: 'BudgetTools',
  CARD_CONTROLS_ONLINE: 'CardControlsOnline',
  CASH_MANAGEMENT: 'CashManagement',
  CHARITABLE_GIVING: 'CharitableGiving',
  CHECK_PROCESSING: 'CheckProcessing',
  CHECK_REORDERING: 'CheckReordering',
  CHECK_REORDERING_BY_ACCOUNT: 'CheckReorderingByAccount',
  CREDIT_CARD_CONTROLS: 'CreditCardControls',
  CREDIT_CARD_FEATURES: 'CreditCardFeatures',
  CREDIT_SCORE: 'CreditScore',
  CU_REWARDS: 'CURewards',
  DEBT_RELIEF: 'DebtRelief',
  DOCUMENTS: 'Documents',
  DOCUMENTS_BY_ACCOUNT: 'DocumentsByAccount',
  DOCUMENTS_SETTINGS: 'DocumentsSettings',
  ESTATUS_CONNECT: 'EStatusConnect',
  FORMS: 'Forms',
  FOREIGN_CURRENCY: 'ForeignCurrency',
  FSCC_PAYMENT: 'FSCCPayment',
  INVOICES: 'Invoices',
  LOAN_ACCOUNT_OPENING: 'LoanAccountOpening',
  LOAN_PAYMENT: 'LoanPayment',
  MANAGE_CREDIT_CARD: 'ManageCreditCard',
  MORTGAGE_SERVICES: 'MortgageServices',
  NETTELLER: 'Netteller',
  RESPONSIVE_BILL_PAY: 'ResponsiveBillPay',
  REWARDS: 'Rewards',
  REWARDS_MAIN: 'RewardsMain',
  TEXT_BANKING: 'TextBanking',
  PAYROLL_PROTECTION_PROGRAM: 'PayrollProtectionProgram',
  POSITIVE_PAY: 'PositivePay',
  POWER_CD_RENEW: 'PowerCDRenew',
  POWER_CHANGE_ADDRESS: 'PowerChangeAddress',
  POWER_LOAN: 'PowerLoan',
  POWER_M2M_TRANSFERS: 'PowerM2MTransfers',
  POWER_OPEN_SUBSHARE: 'PowerShare',
  POWER_OVERDRAFT: 'PowerOverdraft',
  POWER_SKIP_PAYMENT: 'PowerSkipPayment',
  POWER_WITHDRAW_CHECK: 'PowerWithdrawCheck',
  POWER_MAIN_REWARDS: 'PowerMainRewards',
  POWER_MAIN_LOAN_APPLICATION: 'PowerMainLoanApplication',
  POWER_SECONDARY_LOAN_APPLICATION: 'PowerSecondaryLoanApplication',
  POWER_REWARDS: 'PowerRewards',
  PORTFOLIO_MANAGEMENT: 'PortfolioManagement',
  POWER_PERKS: 'PowerPerks',
  CARD_LOCATION_MANAGEMENT: 'CardLocationManagement',
  POWER_PAYMENTS: 'PowerPayments',
  POWER_FORMS: 'PowerForms',
  POWER_DOCUMENTS: 'PowerDocuments',
  POWER_CARD_CONTROLS: 'PowerCardControls',
} as const;
